import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  FolderDown, 
  Clock, 
  Cpu, 
  Coins, 
  Calendar, 
  Download, 
  Eye, 
  Layers,
  FolderOpen,
  Copy,
  Check
} from 'lucide-react';
import { DeliverableFile, Run, MemoryNote } from '@shared/types';

interface DeliverablesViewProps {
  companyId: string;
  runs: Run[];
}

export const DeliverablesView: React.FC<DeliverablesViewProps> = ({
  companyId,
  runs,
}) => {
  const [deliverables, setDeliverables] = useState<DeliverableFile[]>([]);
  const [notes, setNotes] = useState<MemoryNote[]>([]);
  const [selectedFile, setSelectedFile] = useState<DeliverableFile | null>(null);
  const [fileContent, setFileContent] = useState<string>('');
  const [loadingContent, setLoadingContent] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<'deliverables' | 'notes' | 'history'>('deliverables');

  const api = (window as any).nexisFlowAPI;

  const loadFiles = async () => {
    if (!api || !companyId) return;
    try {
      const delivs = await api.listDeliverables(companyId);
      setDeliverables(delivs);
      const mems = await api.listMemoryNotes(companyId);
      setNotes(mems);

      if (delivs.length > 0 && !selectedFile) {
        handleViewFile(delivs[0]);
      }
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    loadFiles();
  }, [companyId]);

  const [copiedContent, setCopiedContent] = useState(false);

  const handleViewFile = async (file: DeliverableFile) => {
    setSelectedFile(file);
    setLoadingContent(true);
    try {
      const content = await api.readDeliverable(companyId, file.relativePath || file.name);
      setFileContent(content);
    } catch (err: any) {
      setFileContent(`Error loading file content: ${err?.message || 'File not found or unreadable'}`);
    } finally {
      setLoadingContent(false);
    }
  };

  const handleOpenFolder = async () => {
    if (!api?.openDirectory) return;
    try {
      await api.openDirectory(companyId);
    } catch (err) {
      console.error('Failed to open directory:', err);
    }
  };

  return (
    <div className="space-y-4">
      {/* View Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-white">Deliverables, Memory & Run History</h3>
          <p className="text-[11px] text-slate-400">
            Persistent workspace outputs generated by your company's agents.
          </p>
        </div>

        {/* Right header actions */}
        <div className="flex items-center space-x-3">
          <button
            type="button"
            onClick={handleOpenFolder}
            className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-xs font-semibold text-slate-200 transition-colors flex items-center space-x-1.5"
            title="Open company workspace folder on your computer"
          >
            <FolderOpen className="w-3.5 h-3.5 text-indigo-400" />
            <span>Open in Explorer</span>
          </button>

          {/* Tab switcher */}
          <div className="flex bg-slate-900 border border-slate-800 rounded-lg p-1">
          <button
            onClick={() => setActiveTab('deliverables')}
            className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
              activeTab === 'deliverables'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Deliverables ({deliverables.length})
          </button>
          <button
            onClick={() => setActiveTab('notes')}
            className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
              activeTab === 'notes'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Company Notes ({notes.length})
          </button>
          <button
            onClick={() => setActiveTab('history')}
            className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
              activeTab === 'history'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Runs History ({runs.length})
          </button>
        </div>
      </div>
    </div>

      {activeTab === 'deliverables' && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 min-h-[500px]">
          {/* File list sidebar */}
          <div className="bg-dark-850 border border-slate-800 rounded-2xl p-3 flex flex-col">
            <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2 px-1">
              Generated Files
            </h4>
            <div className="space-y-1 overflow-y-auto flex-1">
              {deliverables.length === 0 ? (
                <div className="text-center p-8 text-slate-500 text-xs">
                  No deliverables produced yet.
                </div>
              ) : (
                deliverables.map(f => (
                  <button
                    key={f.path}
                    onClick={() => handleViewFile(f)}
                    className={`w-full text-left p-2.5 rounded-lg flex items-center space-x-2.5 transition-all ${
                      selectedFile?.path === f.path
                        ? 'bg-indigo-600 text-white shadow-sm'
                        : 'text-slate-300 hover:bg-slate-800/60'
                    }`}
                  >
                    <FileText className="w-4 h-4 shrink-0" />
                    <div className="truncate flex-1">
                      <p className="text-xs font-medium truncate">{f.name}</p>
                      <p className="text-[10px] opacity-70 font-mono">
                        {(f.sizeBytes / 1024).toFixed(1)} KB • {new Date(f.updatedAt).toLocaleDateString()}
                      </p>
                    </div>
                  </button>
                ))
              )}
            </div>
          </div>

          {/* File Content Preview */}
          <div className="md:col-span-2 bg-dark-850 border border-slate-800 rounded-2xl p-5 flex flex-col">
            {selectedFile ? (
              <div className="flex-1 flex flex-col space-y-3">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <div className="flex items-center space-x-2">
                    <FileText className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs font-bold text-white">{selectedFile.name}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <span className="text-[11px] text-slate-400 font-mono">
                      {selectedFile.relativePath}
                    </span>
                    <button
                      type="button"
                      onClick={() => {
                        navigator.clipboard.writeText(fileContent);
                        setCopiedContent(true);
                        setTimeout(() => setCopiedContent(false), 2000);
                      }}
                      className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-[11px] flex items-center space-x-1 transition-colors cursor-pointer"
                      title="Copy file contents"
                    >
                      {copiedContent ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                      <span>{copiedContent ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                </div>

                <div className="flex-1 bg-slate-900 border border-slate-800 rounded-xl p-4 overflow-y-auto font-mono text-xs text-slate-200 whitespace-pre-wrap leading-relaxed">
                  {loadingContent ? 'Loading...' : fileContent}
                </div>
              </div>
            ) : (
              <div className="h-full flex items-center justify-center text-slate-500 text-xs">
                Select a deliverable file to preview.
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === 'notes' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {notes.length === 0 ? (
            <div className="col-span-2 p-12 text-center text-slate-500 border border-dashed border-slate-800 rounded-2xl text-xs">
              No memory notes written yet. Agents automatically record shared knowledge here.
            </div>
          ) : (
            notes.map(n => (
              <div key={n.id} className="p-4 rounded-xl bg-dark-850 border border-slate-800 space-y-2">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-white">{n.title}</h4>
                  <span className="text-[10px] text-slate-500">{new Date(n.updatedAt).toLocaleDateString()}</span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed font-mono whitespace-pre-wrap bg-slate-900 p-2.5 rounded-lg border border-slate-800/80">
                  {n.content}
                </p>
                {n.tags?.length > 0 && (
                  <div className="flex flex-wrap gap-1 pt-1">
                    {n.tags.map(t => (
                      <span key={t} className="text-[9px] px-1.5 py-0.5 rounded bg-slate-800 text-indigo-300">
                        #{t}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      )}

      {activeTab === 'history' && (
        <div className="space-y-3">
          {runs.length === 0 ? (
            <div className="p-12 text-center text-slate-500 border border-dashed border-slate-800 rounded-2xl text-xs">
              No previous runs recorded. Click "Start Run" on the dashboard to begin.
            </div>
          ) : (
            runs.map(r => (
              <div
                key={r.id}
                className="p-4 rounded-xl bg-dark-850 border border-slate-800 flex items-center justify-between"
              >
                <div className="flex items-center space-x-3">
                  <div className={`w-2.5 h-2.5 rounded-full ${
                    r.status === 'completed' ? 'bg-emerald-400' :
                    r.status === 'failed' ? 'bg-rose-400' :
                    r.status === 'cancelled' ? 'bg-amber-400' :
                    'bg-indigo-400 animate-pulse'
                  }`} />
                  <div>
                    <div className="flex items-center space-x-2">
                      <h4 className="text-xs font-bold text-white font-mono">{r.id}</h4>
                      <span className="text-[10px] uppercase font-bold px-1.5 py-0.2 rounded bg-slate-800 text-slate-400">
                        {r.status}
                      </span>
                    </div>
                    <p className="text-[10px] text-slate-500 mt-0.5">
                      Started: {new Date(r.startedAt).toLocaleString()}
                    </p>
                  </div>
                </div>

                <div className="flex items-center space-x-6 text-xs font-mono">
                  <div className="text-right">
                    <p className="text-slate-400 text-[10px]">Tokens Used</p>
                    <p className="text-indigo-300 font-semibold">{r.totalTokens.toLocaleString()}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-slate-400 text-[10px]">Cost</p>
                    <p className="text-emerald-400 font-semibold">${r.estimatedCost.toFixed(4)}</p>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
};
